.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2018 Mario Frasca <mario@anche.no>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FIBRA 1 "May 17 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH FIBRA
fibra \- cooperative concurrency for Python
.SH SYNOPSIS
.B import fibra
.br
.SH DESCRIPTION
This manual page documents briefly the
.B fibra
module.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBfibra\fP is a Python module that lets you do concurrency in the same thread.  Please have a look at the test suite, to have an idea of how to use this.  Documentation is lacking and contributions are welcome.
.SH OPTIONS
There are no options.
